name: Submission
on:
  pull_request:
    types: [labeled]
jobs:
  submit:
    if: ${{ github.event.label.name == 'Submitted' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
        project:
          - { name: flight-service }
          - { name: passenger-service }
          - { name: baggage-service }
    name: "Submit-test-${{ matrix.project.name }}-${{ matrix.java }}-${{ matrix.project.openai-type }}"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Create env vars
        if: matrix.project.openai-type
        working-directory: ${{ matrix.project.name }}
        run: |
          echo "QUARKUS_PROFILE=${{ matrix.project.openai-type }}" >> $GITHUB_ENV && \
          echo "QUARKUS_TEST_INTEGRATION_TEST_PROFILE=${{ matrix.project.openai-type }}" >> $GITHUB_ENV

      - name: "build-test-jvm-${{ matrix.project.name }}-java-${{ matrix.java }}-${{ matrix.project.openai-type }}"
        working-directory: ${{ matrix.project.name }}
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}